server:
  #启动端口
  port: 9306

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/music/audioCenter/sqlite/audioStation.db?date_string_format=yyyy-MM-dd HH:mm:ss
    username:
    password:

#swagger api信息
swagger:
  api:
    version: 1.0.0
  contact:
    name: anlinxi
    email: anlinxi@gmail.com


# 配置sql打印日志
mybatis-plus:
  typeAliasesPackage: com.faker.audioStation.mapper
  mapper-locations: classpath*:mapper/*.xml, classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  configuration:
    # 嫌日志多可以屏蔽下面这行
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志打印配置
logging:
  level:
    root: INFO
    com.faker: INFO
    com.alibaba: ERROR
    org.jaudiotagger: ERROR


#自定义设置
faker:
  #ffmpeg设置
  ffmpeg:
    #ffmpeg地址设置
    path:
  #音乐文件目录地址
  resources: '/music/'
  #网易云音乐API地址 默认为http://yumbo.top:3000
  music163Api: ''
  #UnblockNeteaseMusic代理端口地址
  unblockNeteaseMusic.proxy: ''
  #开发库反向代理
#  proxy:
#    dev:
#      url: /dev/*
#      #对应web的vue_pc_music项目dev端口
#      target_url: http://127.0.0.1:9902/dev